services:
  - type: web
    name: univer-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 7435
    autoDeploy: true
    healthCheckPath: /
